pipeline{
    agent{
        label "nodejs"
    }
    stages{
        stage("Install dependencies"){
            steps{
                dir('greeting-service'){
                sh "npm ci"
                }
            }
        }

        stage("Check Style"){
            steps{
                sh "npm run lint"
            }
        }

        stage("Test"){
            steps{
                sh "npm test"
            }
        }

        stage('Deploy') {
            steps {
                sh '''
                    oc project shigveR-deploy-strategies
                    oc start-build greeting-service --follow --wait
                '''
            }
        }
    }
}

        // Add the "Deploy" stage here
